services:

    account.security_listener:
        class: AppBundle\Redmine\RedmineUserRegisterListener
        arguments:
            - @security.token_storage
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }


    site_author.listener:
        class: AppBundle\AuthorEditor\AuthorEditorListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    project_type:
        class: AppBundle\Form\ProjectType
        arguments:
            - @router
            - @project_transformer
        tags:
            - { name: form.type, alias: project }

    project_transformer:
            class: AppBundle\Form\ModelTransformer\ProjectModelTransformer
            arguments:
                - @doctrine.orm.entity_manager
                - @projects

    projects:
        class: AppBundle\Redmine\Projects
        arguments:
            - @ekreative_redmine_login.client_provider
            - @security.token_storage
            - @projects_cache

    projects_cache:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - [setRedis, [@redis]]
            - [ setNamespace, [ 'sm:' ]]

    redis:
        class: Redis
        calls:
            - [connect, [%redis%, 6379]]
