parameters:
#    parameter_name: value

services:
    project_type:
        class: AppBundle\Form\ProjectType
        arguments:
            - @router
            - @project_transformer
        tags:
            - { name: form.type, alias: project }

    project_transformer:
            class: AppBundle\Form\ModelTransformer\ProjectModelTransformer
            arguments:
                - @doctrine.orm.entity_manager
                - @projects

    projects:
        class: AppBundle\Redmine\Projects
        arguments:
            - @ekreative_redmine_login.client_provider
            - @security.token_storage
